/* KProcessService.h
   Generated by wsdl2h 2.8.91 from http://localhost:8080/KProcessService/services/KService?wsdl and typemap.dat
   2021-12-08 03:19:53 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/**

@page page_notes Notes

@note HINTS:
 - Run soapcpp2 on KProcessService.h to generate the SOAP/XML processing logic:
   Use soapcpp2 -I to specify paths for #import
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Edit 'typemap.dat' to control namespace bindings and type mappings:
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -c to generate pure C code.
 - Use wsdl2h -R to include the REST operations defined by the WSDLs.
 - Use wsdl2h -O3 or -O4 to optimize by removing unused schema components.
 - Use wsdl2h -d to enable DOM support for xsd:any and xsd:anyType.
 - Use wsdl2h -F to simulate struct-type derivation in C (also works in C++).
 - Use wsdl2h -f to generate flat C++ class hierarchy, removes type derivation.
 - Use wsdl2h -g to generate top-level root elements with readers and writers.
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Use wsdl2h -L to remove this @note and all other @note comments.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE GENERATED soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2019, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c++,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://service.process.k                                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * $CONTAINER                                                                 *
 *   std::vector                                                              *
 *                                                                            *
\******************************************************************************/

#include <vector>
template <class T> class std::vector;

/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to 'typemap.dat' then rerun wsdl2h (use wsdl2h -t typemap.dat):

WS1 = "http://service.process.k"
WS2 = "http://xml.apache.org/xml-soap"

*/

#define SOAP_NAMESPACE_OF_WS1	"http://service.process.k"
//gsoap WS1   schema namespace:	http://service.process.k
//gsoap WS1   schema elementForm:	qualified
//gsoap WS1   schema attributeForm:	unqualified

#define SOAP_NAMESPACE_OF_WS2	"http://xml.apache.org/xml-soap"
//gsoap WS2   schema namespace:	http://xml.apache.org/xml-soap
//gsoap WS2   schema elementForm:	qualified
//gsoap WS2   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/

/// Built-in XSD root type "xs:anyType".
///
/// @note Call virtual method soap_type() generated by soapcpp2 to check runtime type is SOAP_TYPE_xsd__anyType or a derived type.  Use option -P to remove this class.
class xsd__anyType
{ public:
    _XML __item;
    struct soap *soap;
};

/// Built-in type "xs:base64Binary".
class xsd__base64Binary
{ public:
    unsigned char *__ptr;
    int __size;
    char *id, *type, *options; // NOTE: non-NULL for DIME/MIME/MTOM XOP attachments only
};

/// Class wrapper xsd__base64Binary__ for built-in type "xs:base64Binary" extends xsd__anyType.
/// @note Call virtual method soap_type() generated by soapcpp2 to check runtime type is SOAP_TYPE_xsd__base64Binary__ or a derived type.  Use option -P to remove this class.
class xsd__base64Binary__ : public xsd__anyType
{ public:
    xsd__base64Binary                    __item                        ;
};

/// Class wrapper xsd__boolean_ for built-in type "xs:boolean" extends xsd__anyType.
/// @note Call virtual method soap_type() generated by soapcpp2 to check runtime type is SOAP_TYPE_xsd__boolean_ or a derived type.  Use option -P to remove this class.
class xsd__boolean_ : public xsd__anyType
{ public:
    bool                                 __item                        ;
};

/// Class wrapper xsd__string_ for built-in type "xs:string" extends xsd__anyType.
/// @note Call virtual method soap_type() generated by soapcpp2 to check runtime type is SOAP_TYPE_xsd__string_ or a derived type.  Use option -P to remove this class.
class xsd__string_ : public xsd__anyType
{ public:
    std::string                          __item                        ;
};


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


class WS1__GetFileResp;

class WS1__Property;

class WS1__ArrayOfProperty;

class WS1__CreateItemInfo;

class WS1__ArrayOf_USCORExsd_USCOREstring;

class WS1__ArrayOf_USCORExsd_USCOREboolean;

class WS1__CreateItemResp;

class _WS1__getFile;

class _WS1__getFileResponse;

class _WS1__importData;

class _WS1__importDataResponse;

class _WS1__hello;

class _WS1__helloResponse;

class _WS1__createItems;

class _WS1__createItemsResponse;

class WS2__mapItem;

class WS2__Map;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://service.process.k                                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://xml.apache.org/xml-soap                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://service.process.k                                                 *
 *                                                                            *
\******************************************************************************/

/// @brief "http://service.process.k":GetFileResp is a complexType.
///
/// @note class WS1__GetFileResp operations:
/// - WS1__GetFileResp* soap_new_WS1__GetFileResp(soap*) allocate and default initialize
/// - WS1__GetFileResp* soap_new_WS1__GetFileResp(soap*, int num) allocate and default initialize an array
/// - WS1__GetFileResp* soap_new_req_WS1__GetFileResp(soap*, ...) allocate, set required members
/// - WS1__GetFileResp* soap_new_set_WS1__GetFileResp(soap*, ...) allocate, set all public members
/// - WS1__GetFileResp::soap_default(soap*) default initialize members
/// - int soap_read_WS1__GetFileResp(soap*, WS1__GetFileResp*) deserialize from a stream
/// - int soap_write_WS1__GetFileResp(soap*, WS1__GetFileResp*) serialize to a stream
/// - WS1__GetFileResp* WS1__GetFileResp::soap_dup(soap*) returns deep copy of WS1__GetFileResp, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - WS1__GetFileResp::soap_del() deep deletes WS1__GetFileResp data members, use only after WS1__GetFileResp::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int WS1__GetFileResp::soap_type() returns SOAP_TYPE_WS1__GetFileResp or derived type identifier
class WS1__GetFileResp : public xsd__anyType
{ public:
/// Element "fileData" of type xs:base64Binary.
    xsd__base64Binary*                   fileData                       nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "fileName" of type xs:string.
    std::string*                         fileName                       nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "message" of type xs:string.
    std::string*                         message                        nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "success" of type xs:boolean.
    bool                                 success                        1;	///< Required element.
};

/// @brief "http://service.process.k":Property is a complexType.
///
/// @note class WS1__Property operations:
/// - WS1__Property* soap_new_WS1__Property(soap*) allocate and default initialize
/// - WS1__Property* soap_new_WS1__Property(soap*, int num) allocate and default initialize an array
/// - WS1__Property* soap_new_req_WS1__Property(soap*, ...) allocate, set required members
/// - WS1__Property* soap_new_set_WS1__Property(soap*, ...) allocate, set all public members
/// - WS1__Property::soap_default(soap*) default initialize members
/// - int soap_read_WS1__Property(soap*, WS1__Property*) deserialize from a stream
/// - int soap_write_WS1__Property(soap*, WS1__Property*) serialize to a stream
/// - WS1__Property* WS1__Property::soap_dup(soap*) returns deep copy of WS1__Property, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - WS1__Property::soap_del() deep deletes WS1__Property data members, use only after WS1__Property::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int WS1__Property::soap_type() returns SOAP_TYPE_WS1__Property or derived type identifier
class WS1__Property : public xsd__anyType
{ public:
/// Element "propertyName" of type xs:string.
    std::string*                         propertyName                   nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "propertyValue" of type xs:string.
    std::string*                         propertyValue                  nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
};

/// @brief "http://service.process.k":ArrayOfProperty is a complexType.
///
/// @note class WS1__ArrayOfProperty operations:
/// - WS1__ArrayOfProperty* soap_new_WS1__ArrayOfProperty(soap*) allocate and default initialize
/// - WS1__ArrayOfProperty* soap_new_WS1__ArrayOfProperty(soap*, int num) allocate and default initialize an array
/// - WS1__ArrayOfProperty* soap_new_req_WS1__ArrayOfProperty(soap*, ...) allocate, set required members
/// - WS1__ArrayOfProperty* soap_new_set_WS1__ArrayOfProperty(soap*, ...) allocate, set all public members
/// - WS1__ArrayOfProperty::soap_default(soap*) default initialize members
/// - int soap_read_WS1__ArrayOfProperty(soap*, WS1__ArrayOfProperty*) deserialize from a stream
/// - int soap_write_WS1__ArrayOfProperty(soap*, WS1__ArrayOfProperty*) serialize to a stream
/// - WS1__ArrayOfProperty* WS1__ArrayOfProperty::soap_dup(soap*) returns deep copy of WS1__ArrayOfProperty, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - WS1__ArrayOfProperty::soap_del() deep deletes WS1__ArrayOfProperty data members, use only after WS1__ArrayOfProperty::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int WS1__ArrayOfProperty::soap_type() returns SOAP_TYPE_WS1__ArrayOfProperty or derived type identifier
class WS1__ArrayOfProperty : public xsd__anyType
{ public:
/// Vector of WS1__Property* of length 0..unbounded.
    std::vector<WS1__Property*         > item                           0;	///< Multiple elements.
};

/// @brief "http://service.process.k":CreateItemInfo is a complexType.
///
/// @note class WS1__CreateItemInfo operations:
/// - WS1__CreateItemInfo* soap_new_WS1__CreateItemInfo(soap*) allocate and default initialize
/// - WS1__CreateItemInfo* soap_new_WS1__CreateItemInfo(soap*, int num) allocate and default initialize an array
/// - WS1__CreateItemInfo* soap_new_req_WS1__CreateItemInfo(soap*, ...) allocate, set required members
/// - WS1__CreateItemInfo* soap_new_set_WS1__CreateItemInfo(soap*, ...) allocate, set all public members
/// - WS1__CreateItemInfo::soap_default(soap*) default initialize members
/// - int soap_read_WS1__CreateItemInfo(soap*, WS1__CreateItemInfo*) deserialize from a stream
/// - int soap_write_WS1__CreateItemInfo(soap*, WS1__CreateItemInfo*) serialize to a stream
/// - WS1__CreateItemInfo* WS1__CreateItemInfo::soap_dup(soap*) returns deep copy of WS1__CreateItemInfo, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - WS1__CreateItemInfo::soap_del() deep deletes WS1__CreateItemInfo data members, use only after WS1__CreateItemInfo::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int WS1__CreateItemInfo::soap_type() returns SOAP_TYPE_WS1__CreateItemInfo or derived type identifier
class WS1__CreateItemInfo : public xsd__anyType
{ public:
/// Element "itemMasterProperties" of type "http://service.process.k":ArrayOfProperty.
    WS1__ArrayOfProperty*                itemMasterProperties           nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "itemMasterProps" of type "http://xml.apache.org/xml-soap":Map.
    WS2__Map*                            itemMasterProps                nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "itemMasterProps2" of type "http://xml.apache.org/xml-soap":Map.
    WS2__Map*                            itemMasterProps2               nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "itemProperties" of type "http://service.process.k":ArrayOfProperty.
    WS1__ArrayOfProperty*                itemProperties                 nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "itemProps" of type "http://xml.apache.org/xml-soap":Map.
    WS2__Map*                            itemProps                      nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "itemProps2" of type "http://xml.apache.org/xml-soap":Map.
    WS2__Map*                            itemProps2                     nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "itemType" of type xs:string.
    std::string*                         itemType                       nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "revMasterProperties" of type "http://service.process.k":ArrayOfProperty.
    WS1__ArrayOfProperty*                revMasterProperties            nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "revMasterProps" of type "http://xml.apache.org/xml-soap":Map.
    WS2__Map*                            revMasterProps                 nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "revMasterProps2" of type "http://xml.apache.org/xml-soap":Map.
    WS2__Map*                            revMasterProps2                nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "revProperties" of type "http://service.process.k":ArrayOfProperty.
    WS1__ArrayOfProperty*                revProperties                  nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "revProps" of type "http://xml.apache.org/xml-soap":Map.
    WS2__Map*                            revProps                       nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "revProps2" of type "http://xml.apache.org/xml-soap":Map.
    WS2__Map*                            revProps2                      nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
};

/// @brief "http://service.process.k":ArrayOf_xsd_string is a complexType.
///
/// @note class WS1__ArrayOf_USCORExsd_USCOREstring operations:
/// - WS1__ArrayOf_USCORExsd_USCOREstring* soap_new_WS1__ArrayOf_USCORExsd_USCOREstring(soap*) allocate and default initialize
/// - WS1__ArrayOf_USCORExsd_USCOREstring* soap_new_WS1__ArrayOf_USCORExsd_USCOREstring(soap*, int num) allocate and default initialize an array
/// - WS1__ArrayOf_USCORExsd_USCOREstring* soap_new_req_WS1__ArrayOf_USCORExsd_USCOREstring(soap*, ...) allocate, set required members
/// - WS1__ArrayOf_USCORExsd_USCOREstring* soap_new_set_WS1__ArrayOf_USCORExsd_USCOREstring(soap*, ...) allocate, set all public members
/// - WS1__ArrayOf_USCORExsd_USCOREstring::soap_default(soap*) default initialize members
/// - int soap_read_WS1__ArrayOf_USCORExsd_USCOREstring(soap*, WS1__ArrayOf_USCORExsd_USCOREstring*) deserialize from a stream
/// - int soap_write_WS1__ArrayOf_USCORExsd_USCOREstring(soap*, WS1__ArrayOf_USCORExsd_USCOREstring*) serialize to a stream
/// - WS1__ArrayOf_USCORExsd_USCOREstring* WS1__ArrayOf_USCORExsd_USCOREstring::soap_dup(soap*) returns deep copy of WS1__ArrayOf_USCORExsd_USCOREstring, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - WS1__ArrayOf_USCORExsd_USCOREstring::soap_del() deep deletes WS1__ArrayOf_USCORExsd_USCOREstring data members, use only after WS1__ArrayOf_USCORExsd_USCOREstring::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int WS1__ArrayOf_USCORExsd_USCOREstring::soap_type() returns SOAP_TYPE_WS1__ArrayOf_USCORExsd_USCOREstring or derived type identifier
class WS1__ArrayOf_USCORExsd_USCOREstring : public xsd__anyType
{ public:
/// Vector of std::string of length 0..unbounded.
    std::vector<std::string            > item                           0;	///< Multiple elements.
};

/// @brief "http://service.process.k":ArrayOf_xsd_boolean is a complexType.
///
/// @note class WS1__ArrayOf_USCORExsd_USCOREboolean operations:
/// - WS1__ArrayOf_USCORExsd_USCOREboolean* soap_new_WS1__ArrayOf_USCORExsd_USCOREboolean(soap*) allocate and default initialize
/// - WS1__ArrayOf_USCORExsd_USCOREboolean* soap_new_WS1__ArrayOf_USCORExsd_USCOREboolean(soap*, int num) allocate and default initialize an array
/// - WS1__ArrayOf_USCORExsd_USCOREboolean* soap_new_req_WS1__ArrayOf_USCORExsd_USCOREboolean(soap*, ...) allocate, set required members
/// - WS1__ArrayOf_USCORExsd_USCOREboolean* soap_new_set_WS1__ArrayOf_USCORExsd_USCOREboolean(soap*, ...) allocate, set all public members
/// - WS1__ArrayOf_USCORExsd_USCOREboolean::soap_default(soap*) default initialize members
/// - int soap_read_WS1__ArrayOf_USCORExsd_USCOREboolean(soap*, WS1__ArrayOf_USCORExsd_USCOREboolean*) deserialize from a stream
/// - int soap_write_WS1__ArrayOf_USCORExsd_USCOREboolean(soap*, WS1__ArrayOf_USCORExsd_USCOREboolean*) serialize to a stream
/// - WS1__ArrayOf_USCORExsd_USCOREboolean* WS1__ArrayOf_USCORExsd_USCOREboolean::soap_dup(soap*) returns deep copy of WS1__ArrayOf_USCORExsd_USCOREboolean, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - WS1__ArrayOf_USCORExsd_USCOREboolean::soap_del() deep deletes WS1__ArrayOf_USCORExsd_USCOREboolean data members, use only after WS1__ArrayOf_USCORExsd_USCOREboolean::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int WS1__ArrayOf_USCORExsd_USCOREboolean::soap_type() returns SOAP_TYPE_WS1__ArrayOf_USCORExsd_USCOREboolean or derived type identifier
class WS1__ArrayOf_USCORExsd_USCOREboolean : public xsd__anyType
{ public:
/// Vector of bool of length 0..unbounded.
    std::vector<bool                   > item                           0;	///< Multiple elements.
};

/// @brief "http://service.process.k":CreateItemResp is a complexType.
///
/// @note class WS1__CreateItemResp operations:
/// - WS1__CreateItemResp* soap_new_WS1__CreateItemResp(soap*) allocate and default initialize
/// - WS1__CreateItemResp* soap_new_WS1__CreateItemResp(soap*, int num) allocate and default initialize an array
/// - WS1__CreateItemResp* soap_new_req_WS1__CreateItemResp(soap*, ...) allocate, set required members
/// - WS1__CreateItemResp* soap_new_set_WS1__CreateItemResp(soap*, ...) allocate, set all public members
/// - WS1__CreateItemResp::soap_default(soap*) default initialize members
/// - int soap_read_WS1__CreateItemResp(soap*, WS1__CreateItemResp*) deserialize from a stream
/// - int soap_write_WS1__CreateItemResp(soap*, WS1__CreateItemResp*) serialize to a stream
/// - WS1__CreateItemResp* WS1__CreateItemResp::soap_dup(soap*) returns deep copy of WS1__CreateItemResp, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - WS1__CreateItemResp::soap_del() deep deletes WS1__CreateItemResp data members, use only after WS1__CreateItemResp::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int WS1__CreateItemResp::soap_type() returns SOAP_TYPE_WS1__CreateItemResp or derived type identifier
class WS1__CreateItemResp : public xsd__anyType
{ public:
/// Element "messages" of type "http://service.process.k":ArrayOf_xsd_string.
    WS1__ArrayOf_USCORExsd_USCOREstring*  messages                       nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "success" of type "http://service.process.k":ArrayOf_xsd_boolean.
    WS1__ArrayOf_USCORExsd_USCOREboolean*  success                        nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
};

/// @brief Top-level root element "http://service.process.k":getFile
/// @brief "http://service.process.k":getFile is a complexType.
///
/// @note class _WS1__getFile operations:
/// - _WS1__getFile* soap_new__WS1__getFile(soap*) allocate and default initialize
/// - _WS1__getFile* soap_new__WS1__getFile(soap*, int num) allocate and default initialize an array
/// - _WS1__getFile* soap_new_req__WS1__getFile(soap*, ...) allocate, set required members
/// - _WS1__getFile* soap_new_set__WS1__getFile(soap*, ...) allocate, set all public members
/// - _WS1__getFile::soap_default(soap*) default initialize members
/// - int soap_read__WS1__getFile(soap*, _WS1__getFile*) deserialize from a stream
/// - int soap_write__WS1__getFile(soap*, _WS1__getFile*) serialize to a stream
/// - _WS1__getFile* _WS1__getFile::soap_dup(soap*) returns deep copy of _WS1__getFile, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _WS1__getFile::soap_del() deep deletes _WS1__getFile data members, use only after _WS1__getFile::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _WS1__getFile::soap_type() returns SOAP_TYPE__WS1__getFile or derived type identifier
class _WS1__getFile
{ public:
/// Element "id" of type xs:string.
    std::string                          id                             1;	///< Required element.
/// Element "fileName" of type xs:string.
    std::string                          fileName                       1;	///< Required element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://service.process.k":getFileResponse
/// @brief "http://service.process.k":getFileResponse is a complexType.
///
/// @note class _WS1__getFileResponse operations:
/// - _WS1__getFileResponse* soap_new__WS1__getFileResponse(soap*) allocate and default initialize
/// - _WS1__getFileResponse* soap_new__WS1__getFileResponse(soap*, int num) allocate and default initialize an array
/// - _WS1__getFileResponse* soap_new_req__WS1__getFileResponse(soap*, ...) allocate, set required members
/// - _WS1__getFileResponse* soap_new_set__WS1__getFileResponse(soap*, ...) allocate, set all public members
/// - _WS1__getFileResponse::soap_default(soap*) default initialize members
/// - int soap_read__WS1__getFileResponse(soap*, _WS1__getFileResponse*) deserialize from a stream
/// - int soap_write__WS1__getFileResponse(soap*, _WS1__getFileResponse*) serialize to a stream
/// - _WS1__getFileResponse* _WS1__getFileResponse::soap_dup(soap*) returns deep copy of _WS1__getFileResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _WS1__getFileResponse::soap_del() deep deletes _WS1__getFileResponse data members, use only after _WS1__getFileResponse::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _WS1__getFileResponse::soap_type() returns SOAP_TYPE__WS1__getFileResponse or derived type identifier
class _WS1__getFileResponse
{ public:
/// Element "getFileReturn" of type "http://service.process.k":GetFileResp.
    WS1__GetFileResp*                    getFileReturn                  1;	///< Required element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://service.process.k":importData
/// @brief "http://service.process.k":importData is a complexType.
///
/// @note class _WS1__importData operations:
/// - _WS1__importData* soap_new__WS1__importData(soap*) allocate and default initialize
/// - _WS1__importData* soap_new__WS1__importData(soap*, int num) allocate and default initialize an array
/// - _WS1__importData* soap_new_req__WS1__importData(soap*, ...) allocate, set required members
/// - _WS1__importData* soap_new_set__WS1__importData(soap*, ...) allocate, set all public members
/// - _WS1__importData::soap_default(soap*) default initialize members
/// - int soap_read__WS1__importData(soap*, _WS1__importData*) deserialize from a stream
/// - int soap_write__WS1__importData(soap*, _WS1__importData*) serialize to a stream
/// - _WS1__importData* _WS1__importData::soap_dup(soap*) returns deep copy of _WS1__importData, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _WS1__importData::soap_del() deep deletes _WS1__importData data members, use only after _WS1__importData::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _WS1__importData::soap_type() returns SOAP_TYPE__WS1__importData or derived type identifier
class _WS1__importData
{ public:
/// Element "id" of type xs:string.
    std::string                          id                             1;	///< Required element.
/// Element "xmlTemplate" of type xs:string.
    std::string                          xmlTemplate                    1;	///< Required element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://service.process.k":importDataResponse
/// @brief "http://service.process.k":importDataResponse is a complexType.
///
/// @note class _WS1__importDataResponse operations:
/// - _WS1__importDataResponse* soap_new__WS1__importDataResponse(soap*) allocate and default initialize
/// - _WS1__importDataResponse* soap_new__WS1__importDataResponse(soap*, int num) allocate and default initialize an array
/// - _WS1__importDataResponse* soap_new_req__WS1__importDataResponse(soap*, ...) allocate, set required members
/// - _WS1__importDataResponse* soap_new_set__WS1__importDataResponse(soap*, ...) allocate, set all public members
/// - _WS1__importDataResponse::soap_default(soap*) default initialize members
/// - int soap_read__WS1__importDataResponse(soap*, _WS1__importDataResponse*) deserialize from a stream
/// - int soap_write__WS1__importDataResponse(soap*, _WS1__importDataResponse*) serialize to a stream
/// - _WS1__importDataResponse* _WS1__importDataResponse::soap_dup(soap*) returns deep copy of _WS1__importDataResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _WS1__importDataResponse::soap_del() deep deletes _WS1__importDataResponse data members, use only after _WS1__importDataResponse::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _WS1__importDataResponse::soap_type() returns SOAP_TYPE__WS1__importDataResponse or derived type identifier
class _WS1__importDataResponse
{ public:
/// Element "importDataReturn" of type xs:string.
    std::string                          importDataReturn               1;	///< Required element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://service.process.k":hello
/// @brief "http://service.process.k":hello is a complexType.
///
/// @note class _WS1__hello operations:
/// - _WS1__hello* soap_new__WS1__hello(soap*) allocate and default initialize
/// - _WS1__hello* soap_new__WS1__hello(soap*, int num) allocate and default initialize an array
/// - _WS1__hello* soap_new_req__WS1__hello(soap*, ...) allocate, set required members
/// - _WS1__hello* soap_new_set__WS1__hello(soap*, ...) allocate, set all public members
/// - _WS1__hello::soap_default(soap*) default initialize members
/// - int soap_read__WS1__hello(soap*, _WS1__hello*) deserialize from a stream
/// - int soap_write__WS1__hello(soap*, _WS1__hello*) serialize to a stream
/// - _WS1__hello* _WS1__hello::soap_dup(soap*) returns deep copy of _WS1__hello, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _WS1__hello::soap_del() deep deletes _WS1__hello data members, use only after _WS1__hello::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _WS1__hello::soap_type() returns SOAP_TYPE__WS1__hello or derived type identifier
class _WS1__hello
{ public:
/// Element "id" of type xs:string.
    std::string                          id                             1;	///< Required element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://service.process.k":helloResponse
/// @brief "http://service.process.k":helloResponse is a complexType.
///
/// @note class _WS1__helloResponse operations:
/// - _WS1__helloResponse* soap_new__WS1__helloResponse(soap*) allocate and default initialize
/// - _WS1__helloResponse* soap_new__WS1__helloResponse(soap*, int num) allocate and default initialize an array
/// - _WS1__helloResponse* soap_new_req__WS1__helloResponse(soap*, ...) allocate, set required members
/// - _WS1__helloResponse* soap_new_set__WS1__helloResponse(soap*, ...) allocate, set all public members
/// - _WS1__helloResponse::soap_default(soap*) default initialize members
/// - int soap_read__WS1__helloResponse(soap*, _WS1__helloResponse*) deserialize from a stream
/// - int soap_write__WS1__helloResponse(soap*, _WS1__helloResponse*) serialize to a stream
/// - _WS1__helloResponse* _WS1__helloResponse::soap_dup(soap*) returns deep copy of _WS1__helloResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _WS1__helloResponse::soap_del() deep deletes _WS1__helloResponse data members, use only after _WS1__helloResponse::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _WS1__helloResponse::soap_type() returns SOAP_TYPE__WS1__helloResponse or derived type identifier
class _WS1__helloResponse
{ public:
/// Element "helloReturn" of type xs:string.
    std::string                          helloReturn                    1;	///< Required element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://service.process.k":createItems
/// @brief "http://service.process.k":createItems is a complexType.
///
/// @note class _WS1__createItems operations:
/// - _WS1__createItems* soap_new__WS1__createItems(soap*) allocate and default initialize
/// - _WS1__createItems* soap_new__WS1__createItems(soap*, int num) allocate and default initialize an array
/// - _WS1__createItems* soap_new_req__WS1__createItems(soap*, ...) allocate, set required members
/// - _WS1__createItems* soap_new_set__WS1__createItems(soap*, ...) allocate, set all public members
/// - _WS1__createItems::soap_default(soap*) default initialize members
/// - int soap_read__WS1__createItems(soap*, _WS1__createItems*) deserialize from a stream
/// - int soap_write__WS1__createItems(soap*, _WS1__createItems*) serialize to a stream
/// - _WS1__createItems* _WS1__createItems::soap_dup(soap*) returns deep copy of _WS1__createItems, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _WS1__createItems::soap_del() deep deletes _WS1__createItems data members, use only after _WS1__createItems::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _WS1__createItems::soap_type() returns SOAP_TYPE__WS1__createItems or derived type identifier
class _WS1__createItems
{ public:
/// Vector of WS1__CreateItemInfo* of length 1..unbounded.
    std::vector<WS1__CreateItemInfo*   > createItemInfos                1;	///< Multiple elements.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://service.process.k":createItemsResponse
/// @brief "http://service.process.k":createItemsResponse is a complexType.
///
/// @note class _WS1__createItemsResponse operations:
/// - _WS1__createItemsResponse* soap_new__WS1__createItemsResponse(soap*) allocate and default initialize
/// - _WS1__createItemsResponse* soap_new__WS1__createItemsResponse(soap*, int num) allocate and default initialize an array
/// - _WS1__createItemsResponse* soap_new_req__WS1__createItemsResponse(soap*, ...) allocate, set required members
/// - _WS1__createItemsResponse* soap_new_set__WS1__createItemsResponse(soap*, ...) allocate, set all public members
/// - _WS1__createItemsResponse::soap_default(soap*) default initialize members
/// - int soap_read__WS1__createItemsResponse(soap*, _WS1__createItemsResponse*) deserialize from a stream
/// - int soap_write__WS1__createItemsResponse(soap*, _WS1__createItemsResponse*) serialize to a stream
/// - _WS1__createItemsResponse* _WS1__createItemsResponse::soap_dup(soap*) returns deep copy of _WS1__createItemsResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _WS1__createItemsResponse::soap_del() deep deletes _WS1__createItemsResponse data members, use only after _WS1__createItemsResponse::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _WS1__createItemsResponse::soap_type() returns SOAP_TYPE__WS1__createItemsResponse or derived type identifier
class _WS1__createItemsResponse
{ public:
/// Element "createItemsReturn" of type "http://service.process.k":CreateItemResp.
    WS1__CreateItemResp*                 createItemsReturn              1;	///< Required element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://xml.apache.org/xml-soap                                           *
 *                                                                            *
\******************************************************************************/

/// @brief "http://xml.apache.org/xml-soap":mapItem is a complexType.
///
/// @note class WS2__mapItem operations:
/// - WS2__mapItem* soap_new_WS2__mapItem(soap*) allocate and default initialize
/// - WS2__mapItem* soap_new_WS2__mapItem(soap*, int num) allocate and default initialize an array
/// - WS2__mapItem* soap_new_req_WS2__mapItem(soap*, ...) allocate, set required members
/// - WS2__mapItem* soap_new_set_WS2__mapItem(soap*, ...) allocate, set all public members
/// - WS2__mapItem::soap_default(soap*) default initialize members
/// - int soap_read_WS2__mapItem(soap*, WS2__mapItem*) deserialize from a stream
/// - int soap_write_WS2__mapItem(soap*, WS2__mapItem*) serialize to a stream
/// - WS2__mapItem* WS2__mapItem::soap_dup(soap*) returns deep copy of WS2__mapItem, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - WS2__mapItem::soap_del() deep deletes WS2__mapItem data members, use only after WS2__mapItem::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int WS2__mapItem::soap_type() returns SOAP_TYPE_WS2__mapItem or derived type identifier
class WS2__mapItem : public xsd__anyType
{ public:
/// Element "key" of type xs:anyType.
    xsd__anyType*                        key                            nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
/// Element "value" of type xs:anyType.
    xsd__anyType*                        value                          nullptr 1;	///< Required nillable (xsi:nil when NULL) element.
};

/// @brief "http://xml.apache.org/xml-soap":Map is a complexType.
///
/// @note class WS2__Map operations:
/// - WS2__Map* soap_new_WS2__Map(soap*) allocate and default initialize
/// - WS2__Map* soap_new_WS2__Map(soap*, int num) allocate and default initialize an array
/// - WS2__Map* soap_new_req_WS2__Map(soap*, ...) allocate, set required members
/// - WS2__Map* soap_new_set_WS2__Map(soap*, ...) allocate, set all public members
/// - WS2__Map::soap_default(soap*) default initialize members
/// - int soap_read_WS2__Map(soap*, WS2__Map*) deserialize from a stream
/// - int soap_write_WS2__Map(soap*, WS2__Map*) serialize to a stream
/// - WS2__Map* WS2__Map::soap_dup(soap*) returns deep copy of WS2__Map, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - WS2__Map::soap_del() deep deletes WS2__Map data members, use only after WS2__Map::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int WS2__Map::soap_type() returns SOAP_TYPE_WS2__Map or derived type identifier
class WS2__Map : public xsd__anyType
{ public:
/// Vector of WS2__mapItem* of length 0..unbounded.
    std::vector<WS2__mapItem*          > item                           0;	///< Multiple elements.
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://service.process.k                                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://service.process.k                                                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://xml.apache.org/xml-soap                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://xml.apache.org/xml-soap                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap WS1  service name:	KServiceSoapBinding 
//gsoap WS1  service type:	KService 
//gsoap WS1  service port:	http://localhost:8080/KProcessService/services/KService 
//gsoap WS1  service namespace:	http://service.process.k 
//gsoap WS1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref KServiceSoapBinding

@section Service_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/** @page KServiceSoapBinding Binding "KServiceSoapBinding"

@section KServiceSoapBinding_operations Operations of Binding "KServiceSoapBinding"

  - @ref __WS1__getFile

  - @ref __WS1__importData

  - @ref __WS1__hello

  - @ref __WS1__createItems

@section KServiceSoapBinding_ports Default endpoints of Binding "KServiceSoapBinding"

  - http://localhost:8080/KProcessService/services/KService

@note Use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   KServiceSoapBinding                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __WS1__getFile                                                           *
 *                                                                            *
\******************************************************************************/


/** Operation "__WS1__getFile" of service binding "KServiceSoapBinding".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://localhost:8080/KProcessService/services/KService

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___WS1__getFile(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _WS1__getFile*                      WS1__getFile,
    // output parameters:
    _WS1__getFileResponse              &WS1__getFileResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __WS1__getFile(
    struct soap *soap,
    // input parameters:
    _WS1__getFile*                      WS1__getFile,
    // output parameters:
    _WS1__getFileResponse              &WS1__getFileResponse
  );
@endcode

C++ proxy class (defined in soapKServiceSoapBindingProxy.h generated with soapcpp2):
@code
  class KServiceSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapKServiceSoapBindingService.h generated with soapcpp2):
@code
  class KServiceSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap WS1  service method-protocol:	getFile SOAP
//gsoap WS1  service method-style:	getFile document
//gsoap WS1  service method-encoding:	getFile literal
//gsoap WS1  service method-action:	getFile ""
//gsoap WS1  service method-output-action:	getFile Response
int __WS1__getFile(
    _WS1__getFile*                      WS1__getFile,	///< Input parameter
    _WS1__getFileResponse              &WS1__getFileResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __WS1__importData                                                        *
 *                                                                            *
\******************************************************************************/


/** Operation "__WS1__importData" of service binding "KServiceSoapBinding".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://localhost:8080/KProcessService/services/KService

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___WS1__importData(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _WS1__importData*                   WS1__importData,
    // output parameters:
    _WS1__importDataResponse           &WS1__importDataResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __WS1__importData(
    struct soap *soap,
    // input parameters:
    _WS1__importData*                   WS1__importData,
    // output parameters:
    _WS1__importDataResponse           &WS1__importDataResponse
  );
@endcode

C++ proxy class (defined in soapKServiceSoapBindingProxy.h generated with soapcpp2):
@code
  class KServiceSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapKServiceSoapBindingService.h generated with soapcpp2):
@code
  class KServiceSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap WS1  service method-protocol:	importData SOAP
//gsoap WS1  service method-style:	importData document
//gsoap WS1  service method-encoding:	importData literal
//gsoap WS1  service method-action:	importData ""
//gsoap WS1  service method-output-action:	importData Response
int __WS1__importData(
    _WS1__importData*                   WS1__importData,	///< Input parameter
    _WS1__importDataResponse           &WS1__importDataResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __WS1__hello                                                             *
 *                                                                            *
\******************************************************************************/


/** Operation "__WS1__hello" of service binding "KServiceSoapBinding".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://localhost:8080/KProcessService/services/KService

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___WS1__hello(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _WS1__hello*                        WS1__hello,
    // output parameters:
    _WS1__helloResponse                &WS1__helloResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __WS1__hello(
    struct soap *soap,
    // input parameters:
    _WS1__hello*                        WS1__hello,
    // output parameters:
    _WS1__helloResponse                &WS1__helloResponse
  );
@endcode

C++ proxy class (defined in soapKServiceSoapBindingProxy.h generated with soapcpp2):
@code
  class KServiceSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapKServiceSoapBindingService.h generated with soapcpp2):
@code
  class KServiceSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap WS1  service method-protocol:	hello SOAP
//gsoap WS1  service method-style:	hello document
//gsoap WS1  service method-encoding:	hello literal
//gsoap WS1  service method-action:	hello ""
//gsoap WS1  service method-output-action:	hello Response
int __WS1__hello(
    _WS1__hello*                        WS1__hello,	///< Input parameter
    _WS1__helloResponse                &WS1__helloResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __WS1__createItems                                                       *
 *                                                                            *
\******************************************************************************/


/** Operation "__WS1__createItems" of service binding "KServiceSoapBinding".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://localhost:8080/KProcessService/services/KService

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___WS1__createItems(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _WS1__createItems*                  WS1__createItems,
    // output parameters:
    _WS1__createItemsResponse          &WS1__createItemsResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __WS1__createItems(
    struct soap *soap,
    // input parameters:
    _WS1__createItems*                  WS1__createItems,
    // output parameters:
    _WS1__createItemsResponse          &WS1__createItemsResponse
  );
@endcode

C++ proxy class (defined in soapKServiceSoapBindingProxy.h generated with soapcpp2):
@code
  class KServiceSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapKServiceSoapBindingService.h generated with soapcpp2):
@code
  class KServiceSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap WS1  service method-protocol:	createItems SOAP
//gsoap WS1  service method-style:	createItems document
//gsoap WS1  service method-encoding:	createItems literal
//gsoap WS1  service method-action:	createItems ""
//gsoap WS1  service method-output-action:	createItems Response
int __WS1__createItems(
    _WS1__createItems*                  WS1__createItems,	///< Input parameter
    _WS1__createItemsResponse          &WS1__createItemsResponse	///< Output parameter
);

/** @page KServiceSoapBinding Binding "KServiceSoapBinding"

@section KServiceSoapBinding_policy_enablers Policy Enablers of Binding "KServiceSoapBinding"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/** @page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings that are contractually bound by WSDLs and
are auto-generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data
bindings are adopted from XML schemas as part of the WSDL types section or when
running wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

@note The following readers and writers are C/C++ data type (de)serializers
auto-generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

@note Data can be read and deserialized from:
  - an int file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = (int)...
  - a C++ stream (istream, stringstream), using soap->is = (istream*)...
  - a C string, using soap->is = (const char*)...
  - any input, using the soap->frecv() callback

@note Data can be serialized and written to:
  - an int file descriptor, using soap->sendfd = (int)...
  - a socket, using soap->socket = (int)...
  - a C++ stream (ostream, stringstream), using soap->os = (ostream*)...
  - a C string, using soap->os = (const char**)...
  - any output, using the soap->fsend() callback

@note The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_set_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_set_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


*/

/**

@section WS1 Top-level root elements of schema "http://service.process.k"

  - <WS1:getFile> @ref _WS1__getFile
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__WS1__getFile(struct soap*, _WS1__getFile*);
    // Writer (returns SOAP_OK on success):
    soap_write__WS1__getFile(struct soap*, _WS1__getFile*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__WS1__getFile(struct soap*, const char *URL, _WS1__getFile*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__WS1__getFile(struct soap*, const char *URL, _WS1__getFile*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__WS1__getFile(struct soap*, const char *URL, _WS1__getFile*);
    soap_POST_recv__WS1__getFile(struct soap*, _WS1__getFile*);
    @endcode

  - <WS1:getFileResponse> @ref _WS1__getFileResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__WS1__getFileResponse(struct soap*, _WS1__getFileResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__WS1__getFileResponse(struct soap*, _WS1__getFileResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__WS1__getFileResponse(struct soap*, const char *URL, _WS1__getFileResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__WS1__getFileResponse(struct soap*, const char *URL, _WS1__getFileResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__WS1__getFileResponse(struct soap*, const char *URL, _WS1__getFileResponse*);
    soap_POST_recv__WS1__getFileResponse(struct soap*, _WS1__getFileResponse*);
    @endcode

  - <WS1:importData> @ref _WS1__importData
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__WS1__importData(struct soap*, _WS1__importData*);
    // Writer (returns SOAP_OK on success):
    soap_write__WS1__importData(struct soap*, _WS1__importData*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__WS1__importData(struct soap*, const char *URL, _WS1__importData*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__WS1__importData(struct soap*, const char *URL, _WS1__importData*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__WS1__importData(struct soap*, const char *URL, _WS1__importData*);
    soap_POST_recv__WS1__importData(struct soap*, _WS1__importData*);
    @endcode

  - <WS1:importDataResponse> @ref _WS1__importDataResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__WS1__importDataResponse(struct soap*, _WS1__importDataResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__WS1__importDataResponse(struct soap*, _WS1__importDataResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__WS1__importDataResponse(struct soap*, const char *URL, _WS1__importDataResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__WS1__importDataResponse(struct soap*, const char *URL, _WS1__importDataResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__WS1__importDataResponse(struct soap*, const char *URL, _WS1__importDataResponse*);
    soap_POST_recv__WS1__importDataResponse(struct soap*, _WS1__importDataResponse*);
    @endcode

  - <WS1:hello> @ref _WS1__hello
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__WS1__hello(struct soap*, _WS1__hello*);
    // Writer (returns SOAP_OK on success):
    soap_write__WS1__hello(struct soap*, _WS1__hello*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__WS1__hello(struct soap*, const char *URL, _WS1__hello*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__WS1__hello(struct soap*, const char *URL, _WS1__hello*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__WS1__hello(struct soap*, const char *URL, _WS1__hello*);
    soap_POST_recv__WS1__hello(struct soap*, _WS1__hello*);
    @endcode

  - <WS1:helloResponse> @ref _WS1__helloResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__WS1__helloResponse(struct soap*, _WS1__helloResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__WS1__helloResponse(struct soap*, _WS1__helloResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__WS1__helloResponse(struct soap*, const char *URL, _WS1__helloResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__WS1__helloResponse(struct soap*, const char *URL, _WS1__helloResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__WS1__helloResponse(struct soap*, const char *URL, _WS1__helloResponse*);
    soap_POST_recv__WS1__helloResponse(struct soap*, _WS1__helloResponse*);
    @endcode

  - <WS1:createItems> @ref _WS1__createItems
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__WS1__createItems(struct soap*, _WS1__createItems*);
    // Writer (returns SOAP_OK on success):
    soap_write__WS1__createItems(struct soap*, _WS1__createItems*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__WS1__createItems(struct soap*, const char *URL, _WS1__createItems*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__WS1__createItems(struct soap*, const char *URL, _WS1__createItems*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__WS1__createItems(struct soap*, const char *URL, _WS1__createItems*);
    soap_POST_recv__WS1__createItems(struct soap*, _WS1__createItems*);
    @endcode

  - <WS1:createItemsResponse> @ref _WS1__createItemsResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__WS1__createItemsResponse(struct soap*, _WS1__createItemsResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__WS1__createItemsResponse(struct soap*, _WS1__createItemsResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__WS1__createItemsResponse(struct soap*, const char *URL, _WS1__createItemsResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__WS1__createItemsResponse(struct soap*, const char *URL, _WS1__createItemsResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__WS1__createItemsResponse(struct soap*, const char *URL, _WS1__createItemsResponse*);
    soap_POST_recv__WS1__createItemsResponse(struct soap*, _WS1__createItemsResponse*);
    @endcode

*/

/**

@section WS2 Top-level root elements of schema "http://xml.apache.org/xml-soap"

*/

/* End of KProcessService.h */
